### ISSUE TITLE
Missing new message text box

### ISSUE THREAD

**Issue by smilesikand** [shastri9999/kyck#1]
Browser: Chrome
Screen - 15.6"
Resolution - 1366 X 768

![brokerapplications_2](https://cloud.githubusercontent.com/assets/4374085/21807180/8c1cebca-d763-11e6-9aad-2b08e9d28058.JPG)

**Comment by suneelng** [comment]
@abhishekgupta92 
- Message text box issue is fixed.
- But there is a side effect observed on the display of sent items and date & time are shown in correctly (date format is dd/mm/yyyy).
- The response data from the api "usermessage/brokerget" is,
{
  "Status": "SUCCESS",
  "data": [
    {
      "avatar": null,
      "attachName": null,
      "attachType": null,
      "attachMimeType": null,
      "attachUrl": null,
      "brokerageId": 2,
      "contentLength": null,
      "messageId": 5,
      "messageFrom": "broker2@broker.com",
      "messageToName": "user test",
      "messageToEmail": "user2@user.com",
      "messageContent": "hello",
      "messageDate": "01/12/2016 00:00",
      "messageStatus": "READ",
      "messageSubject": "Test ....",
      "messageFromName": "broker2 br2",
      "userId": "user2@user.com"
    },
    {
      "avatar": null,
      "attachName": null,
      "attachType": null,
      "attachMimeType": null,
      "attachUrl": null,
      "brokerageId": 2,
      "contentLength": null,
      "messageId": 6,
      "messageFrom": "user2@user.com",
      "messageToName": "broker2 br2",
      "messageToEmail": "broker2@broker.com",
      "messageContent": "working good",
      "messageDate": "01/12/2016 00:00",
      "messageStatus": "UNREAD",
      "messageSubject": "Test ....",
      "messageFromName": "user2 us2",
      "userId": "user2@user.com"
    },
    {
      "avatar": null,
      "attachName": null,
      "attachType": null,
      "attachMimeType": null,
      "attachUrl": null,
      "brokerageId": 2,
      "contentLength": null,
      "messageId": 100,
      "messageFrom": "broker2@broker.com",
      "messageToName": "jan ten",
      "messageToEmail": "user2@user.com",
      "messageContent": "Testing Messages",
      "messageDate": "03/02/2017 00:00",
      "messageStatus": "UNREAD",
      "messageSubject": "",
      "messageFromName": "broker2 br2",
      "userId": "user2@user.com"
    }
  ],
  "Message": "Successful"
}

Screen Shot:

![image](https://cloud.githubusercontent.com/assets/23191755/22603283/c5069e88-ea6c-11e6-841f-d43e5655a49a.png)

**Comment by abhishekgupta92** [comment]
There is a scroll bar inside the messages.

**Comment by suneelng** [comment]
@abhishekgupta92 

As discussed during the call,
1) The sorting of the inbox and sent messages, inbox on the left and sent on the right.
2) The date information is interpreted incorrectly. it should be in the format "DD/MM/YYYY" 
3) Another input wrt to to submit application, to wait for the the response from the server before changing the tab focus.

**Comment by suneelng** [comment]
1) Need a clarification on the below point,
- The sorting of the inbox and sent messages, inbox on the left and sent on the right.
- Currently the sent items displays on the left side, please clarify.

2) Tab focus is changed to first application from the list when any application is approved or rejected. Requirement is to retain the tab focus to the same application.

**Comment by abhishekgupta92** [comment]
TBD

**Comment by abhishekgupta92** [comment]
1 - data that is coming from server, and it is not coming in the right order (should come from latest to oldest). i pick three of 'em and display

2. yes, my message on left, other person's message on right
