### ISSUE TITLE
Display message - User Dashboard

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#10]
Display of message on dashboard when empty data,
Change to ,
-	No Appointments
-	No Messages

Screen details
1) Chrome
2) 1366 X 768

![user_image_1](https://cloud.githubusercontent.com/assets/23191755/21838507/547d1bb4-d7f8-11e6-833f-98d897a1a0a8.JPG)

**Comment by shastri9999** [comment]
Fixed and test with user account kyckuser@mailinator.com , password: test1234


![screen shot 2017-01-29 at 11 29 04 am](https://cloud.githubusercontent.com/assets/876778/22402264/3c592d9e-e616-11e6-82d2-3faa00632885.png)
