### ISSUE TITLE
Tab Refresh and Document upload

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#12]
-	Cancel option to cancel the upload event when replace event is triggered.
-	The tab data to be refreshed when switching between the tabs. Currently tabs are not refreshed.

Screen details
1) Chrome
2)  1366 X 768

![user_image_3](https://cloud.githubusercontent.com/assets/23191755/21838626/1ed8110c-d7f9-11e6-8ed6-90ef0cb2278c.JPG)

**Comment by shastri9999** [comment]
@suneelng There is no need to referesh document tab, correct?

**Comment by suneelng** [comment]
@shastri9999 

- Tabs requires to be refreshed because there is an auto fill feature from the ocr read data.
- After document upload, the read data is automatically updated to the user and kyc forms and hence refresh of this is needed to show the updated values.
- Reopening only for clarification, if this is taken care then please close the issue.

**Comment by shastri9999** [comment]
Tab is now refreshed every time you navigate to form page. So data is fetched every time.
