### ISSUE TITLE
Submit New Application (Timeslot)

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#14]
-	8 slots display is overflowing to the next date slot.
-	4 timeslots are shown,
o	Select a timeslot after selecting the 3 timeslots, throws an error message but the list is showing the selected 4th timeslot. 
-	Submit brokerage events triggers the API more than one time, last testing resulted in 30 calls !!
-	After submission the screen is changed to tab1 but the data is not refreshed on tab1 and right section “BrokerageApplications”.
- Option/mechanism to delete the selected timeslot.

Screen details
1) Chrome
2) 1366 X 768

![user_image_4](https://cloud.githubusercontent.com/assets/23191755/21838687/736a6d50-d7f9-11e6-8c22-f3c5c0525cc8.JPG)

![user_image_8](https://cloud.githubusercontent.com/assets/23191755/21838686/736a2a3e-d7f9-11e6-9c34-fe69ae37ab3d.JPG)

**Comment by abhishekgupta92** [comment]
8 slots display is overflowing to the next date slot.
FIXED

4 timeslots are shown,
o	Select a timeslot after selecting the 3 timeslots, throws an error message but the list is showing the selected 4th timeslot.
FIXED 

Submit brokerage events triggers the API more than one time, last testing resulted in 30 calls !!
COULDN'T REPRODUCE. TRIED 5 TIMES, WORKED FINE HERE.

After submission the screen is changed to tab1 but the data is not refreshed on tab1 and right section “BrokerageApplications”.
FIXED

Option/mechanism to delete the selected timeslot. ----- NEW FEATURE @smilesikand

**Comment by suneelng** [comment]
@abhishekgupta92 
1) Submit brokerage events triggers the API more than one time, last testing resulted in 30 calls !!
COULDN'T REPRODUCE. TRIED 5 TIMES, WORKED FINE HERE.
- Easy to reproduce, attached the screen shot which is triggered 4 times.
- How to reproduce
i) select 1/2 brokers, 3 time slots for each broker and submit.

2) Option/mechanism to delete the selected timeslot.
- not a new feature, a very basic use-case, when the user selects a timeslot (mistakely) then there should be a way to modfying. current implementation requires restart of application submission process.

Screen shot

![image](https://cloud.githubusercontent.com/assets/23191755/22615291/bac38bf2-eab7-11e6-9473-09b831eb512d.png)

**Comment by abhishekgupta92** [comment]
Fixed 1. 

Please refer to the designs for timeslots. (https://marvelapp.com/18i7c86/screen/16268379). It may seem like a small feature, but this will take me a few hours to work on this as I didn't account for this, initially. cc @smilesikand

**Comment by suneelng** [comment]
@smilesikand 

Kindly come back on the below item.
1) Option/mechanism to delete the selected timeslot.

**Comment by smilesikand** [comment]
as discussed, this would require substantial time to implement. Can up taken up as change request, if required.
