### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#15]
-	Calendar Items are limited to just 5, even when it is more than 5 for a particular date.

**Comment by abhishekgupta92** [comment]
@suneelng there is option for more slots. e.g. 8 slots which on clicking leads to a small popup. cc @smilesikand

**Comment by suneelng** [comment]
@abhishekgupta92 
- I still the more option is limiting the count, attached the screen shot and response data.
- The data are not populated for earlier than jan and few in jan as well.

Response Data:
{
  "Status": "SUCCESS",
  "data": [
    {
      "calendarId": 110,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 05:30",
      "endTime": "26/01/2017 06:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 119,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 05:30",
      "endTime": "26/01/2017 06:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 106,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 05:30",
      "endTime": "26/01/2017 06:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 114,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 05:30",
      "endTime": "26/01/2017 06:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 102,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 04:30",
      "endTime": "26/01/2017 05:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 109,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 04:30",
      "endTime": "26/01/2017 05:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 118,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 04:30",
      "endTime": "26/01/2017 05:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 105,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 04:30",
      "endTime": "26/01/2017 05:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 113,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "26/01/2017 04:30",
      "endTime": "26/01/2017 05:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "broker2",
      "brokerLastName": "br2",
      "brokerEmailId": "broker2@broker.com",
      "brokerName": "LOOP"
    },
    {
      "calendarId": 100,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "25/01/2017 04:30",
      "endTime": "25/01/2017 05:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "Bit",
      "brokerLastName": "Bank",
      "brokerEmailId": "contact@bitbank.com",
      "brokerName": "BIT"
    },
    {
      "calendarId": 103,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "11/01/2017 05:30",
      "endTime": "11/01/2017 06:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "Oly",
      "brokerLastName": "Bank",
      "brokerEmailId": "contact@oly.com",
      "brokerName": "OLY"
    },
    {
      "calendarId": 99,
      "status": "PENDING",
      "meetingSubject": "Discussion about brokerage application",
      "meetingLocation": "Singapore",
      "meetingContent": "Meeting about brokerage application",
      "startTime": "11/01/2017 05:30",
      "endTime": "11/01/2017 06:30",
      "userFirstName": "jan",
      "userLastName": "ten",
      "userEmailId": "user2@user.com",
      "brokerFirstName": "Oly",
      "brokerLastName": "Bank",
      "brokerEmailId": "contact@oly.com",
      "brokerName": "OLY"
    }
  ],
  "Message": "SUCCESSFUL"
}

Screenshot:

1) 
![image](https://cloud.githubusercontent.com/assets/23191755/22615503/9d1481d4-eabb-11e6-84c9-2e56e4de109d.png)

**Comment by abhishekgupta92** [comment]
Can you tell me the login details of this user? Would check.

**Comment by abhishekgupta92** [comment]
I think the issue is that I am using latestuserappointments for showing these appointments, but the output of this API isn't correct. Instead of showing last 10 appointments, it is showing the first 10. Update the API for correct results.

**Comment by suneelng** [comment]
@abhishekgupta92,
- /calender/get/latestuserappointments to be used only to be displayed on dashboard, as it is limited to only 10,
- /calender/get/userappointments to be used to display in the calendar as this will return for a specific month. (Remember this was discussed before)
- Login details for the new link - user1 or user2 or user3@user.com, pw: test123
