### ISSUE TITLE
Brokerage Application (UserApp)

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#18]
- The brokerage Applications section (right side) when the application count exceed certain number. Not sure about the exact number but this is reproducible with 20 + items.

Screen details
1) Chrome
2) 1366 X 768

![user_image_9](https://cloud.githubusercontent.com/assets/23191755/21841677/45466388-d809-11e6-991d-33e780a9733e.JPG)

**Comment by abhishekgupta92** [comment]
FIXED
