### ISSUE TITLE
Broker Dashboard

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#20]
-	Design Issue: Horizontal grey line brokerage application request
-	Start conference button should be enabled only when the appointment is in confirmed state and start conference should be connected to Video conference API (same as in brokerage application summary tab)

Screen details
1.	Chrome
2.	1366 X 768

![user_image_12](https://cloud.githubusercontent.com/assets/23191755/21845497/e6593e8a-d818-11e6-98de-fc51887c41b7.JPG)

**Comment by suneelng** [comment]
@shastri9999 
- Start conference button is not seen even the calendar is confirmed.
- Let me know on what condition the button is shown.

![image](https://cloud.githubusercontent.com/assets/23191755/22615638/f3336fbe-eabe-11e6-98f7-a73efa880932.png)

**Comment by shastri9999** [comment]
You have attached User dashboard screen, the start conference is shown in broker dashboard if status is confirmed.

![screen shot 2017-02-04 at 12 44 12 pm](https://cloud.githubusercontent.com/assets/876778/22616670/b0057714-ead7-11e6-8679-24a4f33c55af.png)

**Comment by suneelng** [comment]
@shastri9999 

- Please refer to this "https://marvelapp.com/18i7c86/screen/16307761", even the user needs join conference, currently there is no way for users to join the video conference.
