### ISSUE TITLE
Brokerage Request

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#21]
-	Documents Download, appointment slots overlaps with the 4 graphs.
-	Missing new message text field right side message section.
-	Say I select a particular application (Darryl Tan), next start the application verification process, jump to summary tab where I have APPROVE or REJECT button.
-	Then I select another application (test janTen), the application data for the selected application is not refreshed and it continues to keep the previous application data. The same goes with the message on the right section.
-	The status information under each application to be fixed to a constant size, currently it varies according to the length of the name.

Screen details
1.	Chrome
2.	1366 X 768

![user_image_13](https://cloud.githubusercontent.com/assets/23191755/21845516/fef7dd7a-d818-11e6-98d1-5517be742737.JPG)
![user_image_14](https://cloud.githubusercontent.com/assets/23191755/21845517/ff212bda-d818-11e6-898f-9dbbadd1c6cd.JPG)

**Comment by abhishekgupta92** [comment]
FIXED all.

**Comment by suneelng** [comment]
@abhishekgupta92 
- The messages data is not updated to the selected application.
- only sometimes it does update, kindly check.
