### ISSUE TITLE
[firefox]: Broker request page

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#24]
- Design Issue - Appointment slots, (refer to the designs).
- Missing new message input field.
- Status information on the graph not shown.
- Scroll bar needs to be similar to chrome.
- 2 scroll bars in the document tabs
- Accept button design (color change)

Screen Details:
1) Firefox
2) 1366x768

![user_image_18](https://cloud.githubusercontent.com/assets/23191755/21863569/06bf5b32-d864-11e6-9b01-2cc2eea70e0c.JPG)

![user_image_19](https://cloud.githubusercontent.com/assets/23191755/21863640/479e88ee-d864-11e6-889f-274a6cf9221b.JPG)

![user_image_20](https://cloud.githubusercontent.com/assets/23191755/21863715/896d72b2-d864-11e6-8374-7c83682240ec.JPG)

**Comment by abhishekgupta92** [comment]
Fixed all. Scroll bar design is dependent on the browser. Latest firefox will give you chrome like designs.

**Comment by suneelng** [comment]
@abhishekgupta92 
- Calendar information appears below the documents section in firefox but beside to documents section in chrome. Can this be same as chrome.
- can we keep the join conference in the same row as date and time information. Currently the two are in two difference lines i believe.


![image](https://cloud.githubusercontent.com/assets/23191755/22616696/0c24c734-ead8-11e6-9a6c-24017b66a62d.png)

**Comment by abhishekgupta92** [comment]
Can't reproduce :( See attached screenshot.

Firefox, 1366x768.
<img width="1427" alt="screen shot 2017-02-06 at 2 22 04 am" src="https://cloud.githubusercontent.com/assets/1681009/22629802/20ebdb9e-ec13-11e6-9a40-a427e23986b0.png">

**Comment by suneelng** [comment]
@abhishekgupta92 

As discussed over the meeting, the appointment slots ui issue. Refer to the above screen shot.

**Comment by abhishekgupta92** [comment]
Since the issue isn't reproduced in my screen, please check if the issue still persists. It is happening since firefox has thicker scroll bars on your laptop.
