### ISSUE TITLE
[firefox]: user dashboard

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#27]
- Missing menu expand collapse icon and the notification icon.
- Scroll button design to be same as the chrome.
- Brokerage applications section to be aligned to same as messages last message.
- account statistic graph does not update with the actual values.

Screen Details
1) Firefox
2) 1366 X 768

![user_image_24](https://cloud.githubusercontent.com/assets/23191755/21882597/2c9bbcb6-d8d1-11e6-9d7e-d0a72695e3e6.JPG)
![user_image_25](https://cloud.githubusercontent.com/assets/23191755/21882598/2c9bec7c-d8d1-11e6-9d59-4c8cedfd96ce.JPG)

**Comment by shastri9999** [comment]
Missing menu expand collapse icon and the notification icon. - Fixed
Scroll button design to be same as the chrome. - Firefox issue. 
Brokerage applications section to be aligned to same as messages last message. - Partially fixed. Exact alignments in  all hieghts is difficult as reducing chart size looks weird. till 760px height fix is done. below that misalignment will be high.
account statistic graph does not update with the actual values. - fixed

**Comment by suneelng** [comment]
@shastri9999 
- can we discuss on point 2 before closing this issue.

**Comment by shastri9999** [comment]
Fixed point 2
