### ISSUE TITLE
User screens: UI bug

### ISSUE THREAD

**Issue by smilesikand** [shastri9999/kyck#3]
Browser: Chrome
Screen - 15.6"
Resolution - 1366 X 768

![brokerageapplication_tab1](https://cloud.githubusercontent.com/assets/4374085/21807499/053031ec-d765-11e6-97d1-6bd16ceef213.JPG)

**Comment by suneelng** [comment]
@abhishekgupta92 
- The last broker is hidden behind the block chain bar.
- Same resolution as initially reported.
- You can use this server (for more data) "http://ec2-54-169-44-116.ap-southeast-1.compute.amazonaws.com/kyck-rest"

Screen shot:
![image](https://cloud.githubusercontent.com/assets/23191755/22603873/21ab727e-ea6f-11e6-9c42-9f52c8857ab9.png)
