### ISSUE TITLE
[Functionality]: Broker messages

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#30]
- Attached files are not shown, but on the user side it is clearly shown that a file is attached and an option to delete as well.
- The attachment button overlaps with the send button.

screen details
1) firefox/chrome
2) 1366x768

![user_image_28](https://cloud.githubusercontent.com/assets/23191755/21886076/39e1ce24-d8e0-11e6-878d-59339a438716.JPG)

**Comment by shastri9999** [comment]
Tested with Broker1 after fix.
I want to highlight delete option comes up for ones being attached, not for ones present.
Below is the screenshot after latest fix

![screen shot 2017-01-29 at 2 14 08 pm](https://cloud.githubusercontent.com/assets/876778/22402904/602f2266-e62d-11e6-95b4-9fc7dff1e277.png)
