### ISSUE TITLE
[Safari]: Side Menu

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#33]
- Design Issue - Side menu in normal expanded mode.

![user_image_4](https://cloud.githubusercontent.com/assets/23191755/21925199/67ff7370-d9a2-11e6-8ccd-82b9966e5b94.png)

**Comment by abhishekgupta92** [comment]
Works fine on my version of Safari. Screenshot attached with version code. Can you please refresh on yours? Else tell me the version code.

<img width="1440" alt="screen shot 2017-01-23 at 12 29 44 pm" src="https://cloud.githubusercontent.com/assets/1681009/22194318/a6a4e57a-e167-11e6-93f5-6dfbc4b0c610.png">


@shastri9999 Do you have any clue about the colors in the charts?
