### ISSUE TITLE
Calendar hover (brokerRequest)

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#35]
- missing profile image as per the design.

Reference Designs:
https://marvelapp.com/18i7c86/screen/16512051

**Comment by abhishekgupta92** [comment]
When does this popup appear? As per the original design, confirm and reschedule options are available without any popup. Check attached screenshot for reference.

<img width="880" alt="screen shot 2017-01-23 at 12 24 38 pm" src="https://cloud.githubusercontent.com/assets/1681009/22194244/14c34e76-e167-11e6-8a68-ce9c747f649a.png">
