### ISSUE TITLE
OCR Preview

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#36]
- Include photo field in the preview.
- Need to discuss with developers on API response data for photo object.

Reference Designs:
https://marvelapp.com/18i7c86/screen/16549473

**Comment by shastri9999** [comment]
@suneelng - The photo being sent from backend is sent in different objects, please fix backend for this. I have accomodated frontend code to handle showing photo if its a base64 string.

Current behavior

{
   "Status":"SUCCESS",
   "data":[
      {
         "name":"IC Number",
         "value":"S7930852H"
      },
      {
         "name":"Photo",
         "value":"<base 64 sting>"
      },
      {
         "name":"PhotoType",
         "value":"image/jpeg"
      },
      {
         "name":"Name",
         "value":"DARRYL TAN CHIN THUAN"
      },
      {
         "name":"Date Of Birth",
         "value":"18-10-1979"
      },
      {
         "name":"Race",
         "value":"CHINESE"
      },
      {
         "name":"Country Of Birth",
         "value":"SINGAPORE"
      },
      {
         "name":"Gender",
         "value":"M"
      }
   ],
   "Message":" Successful"
}

Notice how Photo and PhotoType is in different objects. This wont help as it breaks logic of parsing other fields, where field name and value is in same object. Expected format
[{
         "name":"Country Of Birth",
         "value":"SINGAPORE"
      },
**{name: "field_name", type: "photo", value: "base64 string"},** {
         "name":"Gender",
         "value":"M"
      }]

**Comment by suneelng** [comment]
- There is only one phote possible per document type.
- Discussed with Shastri on the same and we agreed that the current response is good enough and there is no need for any change on the back end.
- Front end will be updated accordingly.

**Comment by shastri9999** [comment]
Fixed according to discussion in commit 5693ead

**Comment by shastri9999** [comment]
assigning back to @suneelng for approval
