### ISSUE TITLE
Video Conference Modl

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#38]
- Cannot close the video conference modal/popup. 

Reference Image/Designs

![image](https://cloud.githubusercontent.com/assets/23191755/21942732/3a1cf1e2-d9f4-11e6-8419-b3a6030c9358.png)

**Comment by suneelng** [comment]
@abhishekgupta92 

- Am unable to get start video conference/join video conference even when the appointment is confirmed.
- Can you confirm when this would be shown.

**Comment by abhishekgupta92** [comment]
@suneelng Not related to this issue. Please create another issue.

**Comment by suneelng** [comment]
@abhishekgupta92 
- Before reporting the issue, i was able to get a join conference button when the appointment was confirmed.
- Now am unable to get this even in confirmed state. I believe this is a related to the same issue.
- Can you confirm when the video conference button would be available as per the implementation.

**Comment by abhishekgupta92** [comment]
Works well for me. No change in this code. Can you please confirm?

**Comment by suneelng** [comment]
@abhishekgupta92 

- Cannot close video conference modal on safari

**Comment by abhishekgupta92** [comment]
Can you show this by sharing screen? Works well on my Safari/Mac.

**Comment by suneelng** [comment]
- Still the close button is missing

- Browser details
i) Firefox, v 52.0
ii) 1680X1050

![image](https://cloud.githubusercontent.com/assets/23191755/23781160/5b0e1e78-0571-11e7-8781-d2dba272c3ad.png)

**Comment by abhishekgupta92** [comment]
ONLY ON SAFARI
