### ISSUE TITLE
Reschedule functionality (Broker Request, brokerApp)

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#39]
- Reschedule functionality does not work as per the requirements when triggered from brokerage request page (broker app)

**Comment by abhishekgupta92** [comment]
@suneelng What differences?

**Comment by smilesikand** [comment]
@suneelng to reproduce with latest commit & let us know, in case issue still persists cc: @abhishekgupta92

**Comment by suneelng** [comment]
@abhishekgupta92 
1) The calendar details shall display information about the broker when the user is logged in. Currently it displays the user information it self. Attached the screen shot.

![image](https://cloud.githubusercontent.com/assets/23191755/22882928/94fe222a-f213-11e6-9d02-dae627c89cf2.png)

2) When i reschedule an existing appointment, it gives an option to select non available slots. It shall display only if the user and broker is available. Incorrect date information is shown on the pop up after selection of the new date and time. In the below screen shot i selected feb 16th and feb 4 is displayed.

![image](https://cloud.githubusercontent.com/assets/23191755/22883063/52513ea2-f214-11e6-8919-d93a5fafedb5.png)

3) After reschedule, logged in as a broker and i see that the appointment information is updated but there is no option to confirm the appointment. It says just re schedule. The is no way to exit the pop up window as well.

![image](https://cloud.githubusercontent.com/assets/23191755/22883233/2ce1bd08-f215-11e6-8908-5f1f7ac75bd8.png)


4) The reschedule pop up screen overlaps the time slot to the next day block. Attached the screen shot.
![image](https://cloud.githubusercontent.com/assets/23191755/22883251/53d37ba4-f215-11e6-8902-2321f6438b1c.png)

5) The pop up window for reschedule does not work on internet explorer.

**Comment by abhishekgupta92** [comment]
1, 2, 3, 4 - done.
5 - Won't work depending on the version.
