### ISSUE TITLE
Calendar Functionality

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#40]
- Reschedule functionality does show all the slots but it should display only available slots.
- Calendar functionality use case and flow (Reschedule/Confirm) is not according to the requirements or what was discussed with coder (Abhishek), kindly revisit the functionality.

![image](https://cloud.githubusercontent.com/assets/23191755/21943026/765ba954-d9f5-11e6-9da7-5368dd42d8c6.png)

![image](https://cloud.githubusercontent.com/assets/23191755/21942976/3934ccfe-d9f5-11e6-8fb2-7274d09530e1.png)

**Comment by abhishekgupta92** [comment]
@suneelng Couldn't understand the bug. Can you please tell more details about it?

cc @smilesikand

**Comment by smilesikand** [comment]
@suneelng to reproduce with latest commit & let us know, in case issue still persists cc: @abhishekgupta92
