### ISSUE TITLE
OCR Preview loading screen to be shown while no data

### ISSUE THREAD

**Issue by shastri9999** [shastri9999/kyck#42]
@suneelng suggested time between upload and OCR data can take few seconds. So we will add loading screen and poll data during this time. Suneel, update status value and assign this to me once done.

**Comment by suneelng** [comment]
@shastri9999 

- Added new api "/document/download/status" which shall return boolean value true/false. True meaning the document is ready for preview, false meaning still under process.
- Input to the api is the documentName.
- Please use server link "http://ec2-54-169-44-116.ap-southeast-1.compute.amazonaws.com/".

**Comment by shastri9999** [comment]
@suneelng I thought only OCR readiness should be checked, entire preview should not be shown? Or only OCR button?

**Comment by suneelng** [comment]
@shastri9999 
Looks like there is some confusion, the preview should be delayed until it is available. The flow is as below,
i) Document upload
ii) OCR engine processing
iii) Save to file server.

step ii & iii and takes about 3-5 seconds. For a better user experience the API can be used before to understand if the document is ready for the preview.

**Comment by shastri9999** [comment]
I have modified frontend, but once its true and I request for OCR this is what is returned from backend for OCR, can you please check 

{"Status":"FAIL","data":"Incorrect result size: expected 1, actual 0","Message":"Invalid Document"}

**Comment by suneelng** [comment]
@shastri9999 
Please try the new link, and try uploading one of the attached documents and please ensure you upload it to IT and nothing else. The above fails due to document validation check.
![iras_4](https://cloud.githubusercontent.com/assets/23191755/22678379/97dd2aa2-ed1f-11e6-96d9-f75d395dd5cc.jpg)

**Comment by shastri9999** [comment]
Fixed.
