### ISSUE TITLE
[NewSideEffect][Broker] - Right side panel dashboard

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#44]
- The right side panel on dashboard truncates as shown below image.
- The behavior is same on all browsers.

Browser details,
- Chrome/safari
- 1680X1050

![image](https://cloud.githubusercontent.com/assets/23191755/23781460/771dc99a-0573-11e7-8859-8d162f999b7f.png)

**Comment by abhishekgupta92** [comment]
TBD

**Comment by abhishekgupta92** [comment]
Fixed.
