### ISSUE TITLE
[NewSideEffect][User] - Submit new broker

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#46]
- After submission of new application the applied broker is still available for selection.
- In the below screen shot a new application is applied to Mbank and it is seen that the Mbank can be selected again. 
- Steps performed,
i) Select Broker
ii) Upload documents
iii) update kyc/personal details
iv) select timeslot and submit
v) tab control transits to tab1 with Mbank selected.

Screen shot:

![image](https://cloud.githubusercontent.com/assets/23191755/23781665/e76f118a-0574-11e7-882f-1c91f115fecd.png)

**Comment by abhishekgupta92** [comment]
- Put a 3 secs timeout. (TBD)
