### ISSUE TITLE
[NewSideEffect][Mobile][User] - Sign up, login

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#47]
1) Device & browser details
- iPhone 6
- Safari

2) Issues 
- Display of country code is not aligned center (dropdown).
- The Agree buttons enables at point 21 and not end of the page.

3) Attachments
![img_7992](https://cloud.githubusercontent.com/assets/23191755/23782945/f01e73d0-057d-11e7-8d8b-16f1d861b7b9.PNG)
![img_7993](https://cloud.githubusercontent.com/assets/23191755/23782946/f01f1f10-057d-11e7-8ee1-9e7bc677995b.PNG)
![img_7994](https://cloud.githubusercontent.com/assets/23191755/23782947/f01f922e-057d-11e7-9fc5-998786c9bb1c.PNG)

**Comment by shastri9999** [comment]
Fixed in commit - cec9777
Fixed scroll issue and alignment issue. Checked with safari and chrome emulator.
