### ISSUE TITLE
User: Document Preview: Zoom in/out missing; OCR preview UI bug

### ISSUE THREAD

**Issue by smilesikand** [shastri9999/kyck#5]
Browser: Chrome
Screen - 15.6"
Resolution - 1366 X 768

![documentpreview](https://cloud.githubusercontent.com/assets/4374085/21807547/3c184852-d765-11e6-8ffd-b7841018187c.JPG)

**Comment by shastri9999** [comment]
@suneelng Buttons are now visible
Zoom in, Zoom out is always on mouse scroll

**Comment by suneelng** [comment]
@shastri9999 
- Zoom in and out does not work with mouse scroll.

**Comment by shastri9999** [comment]
@smilesikand Can you check this behaviour once?

**Comment by shastri9999** [comment]
From issue#9 -- Tracking here, The image preview is out of the modal window.
Resolution: 1366x768, chrome
the loading bar (screen loading) is always active when the page is refreshed when current page is pointing to document

**Comment by shastri9999** [comment]
The zoom in/ zoom out works once canvas is activated during crop. This was clarified to suneel on call. So I think this can be marked complete. @smilesikand
