### ISSUE TITLE
[NewSideEffect][Mobile][User] - Document, OCR Preview and message badge

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#50]
1) Device & browser details
- iPhone 6
- Safari

2) Issues 
- Document preview exceed the boundary of the oCR preview window.
- OCR preview has few fields greyed out.
- Message badge information is not aligned to center.

3) Attachments

![img_7996](https://cloud.githubusercontent.com/assets/23191755/23783129/13e11952-057f-11e7-9d8d-26b5882f3255.PNG)

![img_8006](https://cloud.githubusercontent.com/assets/23191755/23783146/4a44753e-057f-11e7-8254-753e4ad2d0b2.PNG)

**Comment by shastri9999** [comment]
Fixed in commit b5ec9b5, fixed aligment of messages count checked on safari and chrome of mobile device
