### ISSUE TITLE
[NewSideEffect][Mobile][Common] - Messages

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#51]
1) Device & browser details
- iPhone 6
- Safari

2) Issues 
- Display of messages overlaps shall be re worked to fix the design issues, the date/time fields is outside the boundary.

3) Attachments
![img_8007](https://cloud.githubusercontent.com/assets/23191755/23783183/9b2d5bc8-057f-11e7-9f91-f0badf0af3dc.PNG)
![img_8012](https://cloud.githubusercontent.com/assets/23191755/23783189/adba9030-057f-11e7-86fa-87acb3261784.PNG)

**Comment by abhishekgupta92** [comment]
Works well on Simulator.

**Comment by shastri9999** [comment]
Fixed in commit 0dd13ff
