### ISSUE TITLE
[NewSideEffect][Mobile][Broker] - Broker request 

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#52]
1) Device & browser details
- iPhone 6
- Safari

2) Issues 
- The right side bar is not shown until the height of the device.
- In the application summary the components are left aligned, it shall be center aligned and the horizontal scroll shall be removed.

3) Attachments

![img_8008](https://cloud.githubusercontent.com/assets/23191755/23783236/12b26ee0-0580-11e7-92e8-e60fc61bb979.PNG)
![img_8009](https://cloud.githubusercontent.com/assets/23191755/23783238/12b2c052-0580-11e7-8ce6-7a68cdaf56c6.PNG)
![img_8010](https://cloud.githubusercontent.com/assets/23191755/23783239/12b34022-0580-11e7-948f-a573dd959af5.PNG)
![img_8011](https://cloud.githubusercontent.com/assets/23191755/23783237/12b2b0bc-0580-11e7-8930-d5b18eb9d4e8.PNG)

**Comment by abhishekgupta92** [comment]
TBD

1 - The right side bar is not shown until the height of the device. (Replace with a new image)
2 - Remove scroll bar for validation
3 - Center Align
