### ISSUE TITLE
Profile Tab: Change address field to text area

### ISSUE THREAD

**Issue by smilesikand** [shastri9999/kyck#8]
Browser: Chrome
Screen - 15.6"
Resolution - 1366 X 768
![profiletab](https://cloud.githubusercontent.com/assets/4374085/21807625/a9cf16aa-d765-11e6-88e3-2081c6c4bf1c.JPG)

**Comment by shastri9999** [comment]
@suneelng In my testing I notice backend is sending this as response now

```{"Status":"SUCCESS","data":[{"questionId":1,"questionDesc":"Gender","answerDesc":"Female","answerText":"null","answerId":2,"questionType":"RADIO","validationType":"RADIO","requireField":"OPTIONAL","answersList":[{"answerId":"1","answerDescription":"Male"},{"answerId":"2","answerDescription":"Female"}]},{"questionId":2,"questionDesc":"Passport No.","answerDesc":null,"answerText":"kljlj","answerId":0,"questionType":"TEXT","validationType":"TEXT","requireField":"REQUIRED","answersList":[]},{"questionId":3,"questionDesc":"NRIC No.","answerDesc":null,"answerText":"lkjlk","answerId":0,"questionType":"TEXT","validationType":"TEXT","requireField":"REQUIRED","answersList":[]},{"questionId":4,"questionDesc":"Residential Phone","answerDesc":null,"answerText":"9880546562","answerId":0,"questionType":"TEXT","validationType":"PHONE","requireField":"OPTIONAL","answersList":[]},{"questionId":5,"questionDesc":"Nationality","answerDesc":"Anguilla","answerText":"null","answerId":14,"questionType":"DROPDOWN","validationType":"DROPDOWN","requireField":"OPTIONAL","answersList":[{"answerId":"8","answerDescription":"Åland Islands"},{"answerId":"9","answerDescription":"Albania"},{"answerId":"10","answerDescription":"Algeria"},{"answerId":"11","answerDescription":"American Samoa"},{"answerId":"12","answerDescription":"AndorrA"},{"answerId":"13","answerDescription":"Angola"},{"answerId":"14","answerDescription":"Anguilla"},{"answerId":"15","answerDescription":"Antarctica"},{"answerId":"16","answerDescription":"Antigua and Barbuda"},{"answerId":"17","answerDescription":"Argentina"},{"answerId":"18","answerDescription":"Armenia"},{"answerId":"19","answerDescription":"Aruba"},{"answerId":"20","answerDescription":"Australia"},{"answerId":"21","answerDescription":"Austria"},{"answerId":"22","answerDescription":"Azerbaijan"},{"answerId":"23","answerDescription":"Bahamas"},{"answerId":"24","answerDescription":"Bahrain"},{"answerId":"25","answerDescription":"Bangladesh"},{"answerId":"26","answerDescription":"Barbados"},{"answerId":"27","answerDescription":"Belarus"},{"answerId":"28","answerDescription":"Belgium"},{"answerId":"29","answerDescription":"Belize"},{"answerId":"30","answerDescription":"Benin"},{"answerId":"31","answerDescription":"Bermuda"},{"answerId":"32","answerDescription":"Bhutan"},{"answerId":"33","answerDescription":"Bolivia"},{"answerId":"34","answerDescription":"Bosnia and Herzegovina"},{"answerId":"35","answerDescription":"Botswana"},{"answerId":"36","answerDescription":"Bouvet Island"},{"answerId":"37","answerDescription":"Brazil"},{"answerId":"38","answerDescription":"British Indian Ocean Territory"},{"answerId":"39","answerDescription":"Brunei Darussalam"},{"answerId":"40","answerDescription":"Bulgaria"},{"answerId":"41","answerDescription":"Burkina Faso"},{"answerId":"42","answerDescription":"Burundi"},{"answerId":"43","answerDescription":"Cambodia"},{"answerId":"44","answerDescription":"Cameroon"},{"answerId":"45","answerDescription":"Canada"},{"answerId":"46","answerDescription":"Cape Verde"},{"answerId":"47","answerDescription":"Cayman Islands"},{"answerId":"48","answerDescription":"Central African Republic"},{"answerId":"49","answerDescription":"Chad"},{"answerId":"50","answerDescription":"Chile"},{"answerId":"51","answerDescription":"China"},{"answerId":"52","answerDescription":"Christmas Island"},{"answerId":"53","answerDescription":"Cocos (Keeling) Islands"},{"answerId":"54","answerDescription":"Colombia"},{"answerId":"55","answerDescription":"Comoros"},{"answerId":"56","answerDescription":"Congo"},{"answerId":"57","answerDescription":"Congo, The Democratic Republic of the"},{"answerId":"58","answerDescription":"Cook Islands"},{"answerId":"59","answerDescription":"Costa Rica"},{"answerId":"60","answerDescription":"Cote D"},{"answerId":"61","answerDescription":"Croatia"},{"answerId":"62","answerDescription":"Cuba"},{"answerId":"63","answerDescription":"Cyprus"},{"answerId":"64","answerDescription":"Czech Republic"},{"answerId":"65","answerDescription":"Denmark"},{"answerId":"66","answerDescription":"Djibouti"},{"answerId":"67","answerDescription":"Dominica"},{"answerId":"68","answerDescription":"Dominican Republic"},{"answerId":"69","answerDescription":"Ecuador"},{"answerId":"70","answerDescription":"Egypt"},{"answerId":"71","answerDescription":"El Salvador"},{"answerId":"72","answerDescription":"Equatorial Guinea"},{"answerId":"73","answerDescription":"Eritrea"},{"answerId":"74","answerDescription":"Estonia"},{"answerId":"75","answerDescription":"Ethiopia"},{"answerId":"76","answerDescription":"Falkland Islands (Malvinas)"},{"answerId":"77","answerDescription":"Faroe Islands"},{"answerId":"78","answerDescription":"Fiji"},{"answerId":"79","answerDescription":"Finland"},{"answerId":"80","answerDescription":"France"},{"answerId":"81","answerDescription":"French Guiana"},{"answerId":"82","answerDescription":"French Polynesia"},{"answerId":"83","answerDescription":"French Southern Territories"},{"answerId":"84","answerDescription":"Gabon"},{"answerId":"85","answerDescription":"Gambia"},{"answerId":"86","answerDescription":"Georgia"},{"answerId":"87","answerDescription":"Germany"},{"answerId":"88","answerDescription":"Ghana"},{"answerId":"89","answerDescription":"Gibraltar"},{"answerId":"90","answerDescription":"Greece"},{"answerId":"91","answerDescription":"Greenland"},{"answerId":"92","answerDescription":"Grenada"},{"answerId":"93","answerDescription":"Guadeloupe"},{"answerId":"94","answerDescription":"Guam"},{"answerId":"95","answerDescription":"Guatemala"},{"answerId":"96","answerDescription":"Guernsey"},{"answerId":"97","answerDescription":"Guinea"},{"answerId":"98","answerDescription":"Guinea-Bissau"},{"answerId":"99","answerDescription":"Guyana"},{"answerId":"100","answerDescription":"Haiti"},{"answerId":"101","answerDescription":"Heard Island and Mcdonald Islands"},{"answerId":"102","answerDescription":"Holy See (Vatican City State)"},{"answerId":"103","answerDescription":"Honduras"},{"answerId":"104","answerDescription":"Hong Kong"},{"answerId":"105","answerDescription":"Hungary"},{"answerId":"106","answerDescription":"Iceland"},{"answerId":"107","answerDescription":"India"},{"answerId":"108","answerDescription":"Indonesia"},{"answerId":"109","answerDescription":"Iran, Islamic Republic Of"},{"answerId":"110","answerDescription":"Iraq"},{"answerId":"111","answerDescription":"Ireland"},{"answerId":"112","answerDescription":"Isle of Man"},{"answerId":"113","answerDescription":"Israel"},{"answerId":"114","answerDescription":"Italy"},{"answerId":"115","answerDescription":"Jamaica"},{"answerId":"116","answerDescription":"Japan"},{"answerId":"117","answerDescription":"Jersey"},{"answerId":"118","answerDescription":"Jordan"},{"answerId":"119","answerDescription":"Kazakhstan"},{"answerId":"120","answerDescription":"Kenya"},{"answerId":"121","answerDescription":"Kiribati"},{"answerId":"122","answerDescription":"Korea, Democratic People"},{"answerId":"123","answerDescription":"Korea, Republic of"},{"answerId":"124","answerDescription":"Kuwait"},{"answerId":"125","answerDescription":"Kyrgyzstan"},{"answerId":"126","answerDescription":"Lao People"},{"answerId":"127","answerDescription":"Latvia"},{"answerId":"128","answerDescription":"Lebanon"},{"answerId":"129","answerDescription":"Lesotho"},{"answerId":"130","answerDescription":"Liberia"},{"answerId":"131","answerDescription":"Libyan Arab Jamahiriya"},{"answerId":"132","answerDescription":"Liechtenstein"},{"answerId":"133","answerDescription":"Lithuania"},{"answerId":"134","answerDescription":"Luxembourg"},{"answerId":"135","answerDescription":"Macao"},{"answerId":"136","answerDescription":"Macedonia, The Former Yugoslav Republic of"},{"answerId":"137","answerDescription":"Madagascar"},{"answerId":"138","answerDescription":"Malawi"},{"answerId":"139","answerDescription":"Malaysia"},{"answerId":"140","answerDescription":"Maldives"},{"answerId":"141","answerDescription":"Mali"},{"answerId":"142","answerDescription":"Malta"},{"answerId":"143","answerDescription":"Marshall Islands"},{"answerId":"144","answerDescription":"Martinique"},{"answerId":"145","answerDescription":"Mauritania"},{"answerId":"146","answerDescription":"Mauritius"},{"answerId":"147","answerDescription":"Mayotte"},{"answerId":"148","answerDescription":"Mexico"},{"answerId":"149","answerDescription":"Micronesia, Federated States of"},{"answerId":"150","answerDescription":"Moldova, Republic of"},{"answerId":"151","answerDescription":"Monaco"},{"answerId":"152","answerDescription":"Mongolia"},{"answerId":"153","answerDescription":"Montserrat"},{"answerId":"154","answerDescription":"Morocco"},{"answerId":"155","answerDescription":"Mozambique"},{"answerId":"156","answerDescription":"Myanmar"},{"answerId":"157","answerDescription":"Namibia"},{"answerId":"158","answerDescription":"Nauru"},{"answerId":"159","answerDescription":"Nepal"},{"answerId":"160","answerDescription":"Netherlands"},{"answerId":"161","answerDescription":"Netherlands Antilles"},{"answerId":"162","answerDescription":"New Caledonia"},{"answerId":"163","answerDescription":"New Zealand"},{"answerId":"164","answerDescription":"Nicaragua"},{"answerId":"165","answerDescription":"Niger"},{"answerId":"166","answerDescription":"Nigeria"},{"answerId":"167","answerDescription":"Niue"},{"answerId":"168","answerDescription":"Norfolk Island"},{"answerId":"169","answerDescription":"Northern Mariana Islands"},{"answerId":"170","answerDescription":"Norway"},{"answerId":"171","answerDescription":"Oman"},{"answerId":"172","answerDescription":"Pakistan"},{"answerId":"173","answerDescription":"Palau"},{"answerId":"174","answerDescription":"Palestinian Territory, Occupied"},{"answerId":"175","answerDescription":"Panama"},{"answerId":"176","answerDescription":"Papua New Guinea"},{"answerId":"177","answerDescription":"Paraguay"},{"answerId":"178","answerDescription":"Peru"},{"answerId":"179","answerDescription":"Philippines"},{"answerId":"180","answerDescription":"Pitcairn"},{"answerId":"181","answerDescription":"Poland"},{"answerId":"182","answerDescription":"Portugal"},{"answerId":"183","answerDescription":"Puerto Rico"},{"answerId":"184","answerDescription":"Qatar"},{"answerId":"185","answerDescription":"Reunion"},{"answerId":"186","answerDescription":"Romania"},{"answerId":"187","answerDescription":"Russian Federation"},{"answerId":"188","answerDescription":"RWANDA"},{"answerId":"189","answerDescription":"Saint Helena"},{"answerId":"190","answerDescription":"Saint Kitts and Nevis"},{"answerId":"191","answerDescription":"Saint Lucia"},{"answerId":"192","answerDescription":"Saint Pierre and Miquelon"},{"answerId":"193","answerDescription":"Saint Vincent and the Grenadines"},{"answerId":"194","answerDescription":"Samoa"},{"answerId":"195","answerDescription":"San Marino"},{"answerId":"196","answerDescription":"Sao Tome and Principe"},{"answerId":"197","answerDescription":"Saudi Arabia"},{"answerId":"198","answerDescription":"Senegal"},{"answerId":"199","answerDescription":"Serbia and Montenegro"},{"answerId":"200","answerDescription":"Seychelles"},{"answerId":"201","answerDescription":"Sierra Leone"},{"answerId":"202","answerDescription":"Singapore"},{"answerId":"203","answerDescription":"Slovakia"},{"answerId":"204","answerDescription":"Slovenia"},{"answerId":"205","answerDescription":"Solomon Islands"},{"answerId":"206","answerDescription":"Somalia"},{"answerId":"207","answerDescription":"South Africa"},{"answerId":"208","answerDescription":"South Georgia and the South Sandwich Islands"},{"answerId":"209","answerDescription":"Spain"},{"answerId":"210","answerDescription":"Sri Lanka"},{"answerId":"211","answerDescription":"Sudan"},{"answerId":"212","answerDescription":"Suriname"},{"answerId":"213","answerDescription":"Svalbard and Jan Mayen"},{"answerId":"214","answerDescription":"Swaziland"},{"answerId":"215","answerDescription":"Sweden"},{"answerId":"216","answerDescription":"Switzerland"},{"answerId":"217","answerDescription":"Syrian Arab Republic"},{"answerId":"218","answerDescription":"Taiwan, Province of China"},{"answerId":"219","answerDescription":"Tajikistan"},{"answerId":"220","answerDescription":"Tanzania, United Republic of"},{"answerId":"221","answerDescription":"Thailand"},{"answerId":"222","answerDescription":"Timor-Leste"},{"answerId":"223","answerDescription":"Togo"},{"answerId":"224","answerDescription":"Tokelau"},{"answerId":"225","answerDescription":"Tonga"},{"answerId":"226","answerDescription":"Trinidad and Tobago"},{"answerId":"227","answerDescription":"Tunisia"},{"answerId":"228","answerDescription":"Turkey"},{"answerId":"229","answerDescription":"Turkmenistan"},{"answerId":"230","answerDescription":"Turks and Caicos Islands"},{"answerId":"231","answerDescription":"Tuvalu"},{"answerId":"232","answerDescription":"Uganda"},{"answerId":"233","answerDescription":"Ukraine"},{"answerId":"234","answerDescription":"United Arab Emirates"},{"answerId":"235","answerDescription":"United Kingdom"},{"answerId":"236","answerDescription":"United States"},{"answerId":"237","answerDescription":"United States Minor Outlying Islands"},{"answerId":"238","answerDescription":"Uruguay"},{"answerId":"239","answerDescription":"Uzbekistan"},{"answerId":"240","answerDescription":"Vanuatu"},{"answerId":"241","answerDescription":"Venezuela"},{"answerId":"242","answerDescription":"Viet Nam"},{"answerId":"243","answerDescription":"Virgin Islands, British"},{"answerId":"244","answerDescription":"Virgin Islands, U.S."},{"answerId":"245","answerDescription":"Wallis and Futuna"},{"answerId":"246","answerDescription":"Western Sahara"},{"answerId":"247","answerDescription":"Yemen"},{"answerId":"248","answerDescription":"Zambia"},{"answerId":"249","answerDescription":"Zimbabwe"}]},{"questionId":6,"questionDesc":"Residential Address","answerDesc":null,"answerText":"Singapore","answerId":0,"questionType":"TEXT","validationType":"TEXT","requireField":"OPTIONAL","answersList":[]},{"questionId":7,"questionDesc":"Mailing Address","answerDesc":null,"answerText":"null","answerId":0,"questionType":"TEXT","validationType":"TEXT","requireField":"OPTIONAL","answersList":[]},{"questionId":8,"questionDesc":"Employment Status","answerDesc":"Housewife","answerText":"null","answerId":6,"questionType":"DROPDOWN","validationType":"DROPDOWN","requireField":"REQUIRED","answersList":[{"answerId":"3","answerDescription":"Self-Employed"},{"answerId":"4","answerDescription":"Employed"},{"answerId":"5","answerDescription":"UnEmployed"},{"answerId":"6","answerDescription":"Housewife"},{"answerId":"7","answerDescription":"Retired"}]},{"questionId":9,"questionDesc":"Employer Name","answerDesc":null,"answerText":"lkjkl","answerId":0,"questionType":"TEXT","validationType":"TEXT","requireField":"REQUIRED","answersList":[]},{"questionId":10,"questionDesc":"Employer Address","answerDesc":null,"answerText":"kjlkj","answerId":0,"questionType":"TEXT","validationType":"TEXT","requireField":"REQUIRED","answersList":[]},{"questionId":11,"questionDesc":"Years of Service","answerDesc":null,"answerText":"11","answerId":0,"questionType":"NUMBER","validationType":"NUMBER","requireField":"REQUIRED","answersList":[]},{"questionId":12,"questionDesc":"Nature of Business","answerDesc":null,"answerText":"kljlkj","answerId":0,"questionType":"TEXT","validationType":"TEXT","requireField":"REQUIRED","answersList":[]},{"questionId":13,"questionDesc":"Date of Birth","answerDesc":null,"answerText":"02-11-1987","answerId":0,"questionType":"DATE","validationType":"DATE","requireField":"OPTIONAL","answersList":[]}],"Message":" Successful"}```

I have made changes to consider questionType TEXTAREA, but backend still sends mailing address as TEXT, assigning it to you to fix backend.

**Comment by suneelng** [comment]
- Even upon changing to TEXTAREA it still shows as text field and not text area.
- Please use this for server "http://ec2-54-169-44-116.ap-southeast-1.compute.amazonaws.com/"

**Comment by shastri9999** [comment]
Fix in e0a9885, check now. validationType and questionType was interchanged in frontend for this. It has been rectified.
